---
title: "Tugas-Naives-Bayes"
output: html_document
author: "vincensius damar adyatma"
---

```{r}
library(caret)
```

```{r}
#menampilkan working directory yang aktif sekarang
getwd()
```
```{r}
#membaca dataset iris
data = read.csv("./dataset/Iris.csv")
data
```

```{r}
#menghilangkan kolom/feature id

data <- data[, -1]
data
```

```{r}
#mengubah kolom species menjad tipe kolom factor atau kategorikal
data$Species = factor(data$Species)
str(data)
```
```{r}
#membagi dataset menjadi 70% data training dan 30% data test
index <- createDataPartition(data$Species, p = 0.7, list = FALSE)
data.train <- data[index,]
data.test <- data[-index,]
```

```{r}
# Membuat kontrol cross validation dengan jumlah folds 10
crossValidationControl = trainControl(method = 'cv',number = 10)
```

```{r}
# Melatih model dengan cross validation dan algoritma naive bayes
fit.cv <- train(Species ~ ., data = data.train, method = "naive_bayes", trControl = crossValidationControl)


fit.cv
```
```{r}
#menampilkan hasil pohon keputusan
plot(fit.cv$finalModel)
```
```{r}
#melakukan prediksi dengan data test
pred <- predict(fit.cv, data.test)
pred
```
```{r}
# Membuat tabel confusion matrix dari actual vs predicted
confusionMatrix(table(data.test$Species,pred))
```
```{r}
#Menampilkan grafik akurasi corss validation
plot(fit.cv)
```

